// Mock job data to simulate job listings from different sources

export const mockJobs = [
  {
    id: "1",
    title: "Senior Software Engineer",
    company: "TechCorp Solutions",
    location: "San Francisco, CA",
    remote: true,
    description: "We are looking for a Senior Software Engineer to join our growing team. You will be responsible for developing high-quality applications, collaborating with cross-functional teams, and mentoring junior developers. The ideal candidate has strong experience with React, Node.js, and cloud technologies.",
    jobType: "full-time",
    experienceLevel: "senior",
    salaryMin: 120000,
    salaryMax: 160000,
    postedDate: "2023-05-10T08:00:00Z",
    applicants: 78,
    skills: ["React", "Node.js", "AWS", "TypeScript", "MongoDB"],
    companyLogo: "https://ui-avatars.com/api/?name=T&background=0D8ABC&color=fff&size=100",
    source: "linkedin",
    applyUrl: "https://linkedin.com/jobs/view/senior-software-engineer"
  },
  {
    id: "2",
    title: "Product Manager",
    company: "InnovateTech",
    location: "New York, NY",
    remote: false,
    description: "InnovateTech is seeking an experienced Product Manager to lead our product development initiatives. You will work closely with engineering, design, and marketing teams to define product strategy and roadmap. The ideal candidate has a proven track record of delivering successful products and a deep understanding of user-centered design principles.",
    jobType: "full-time",
    experienceLevel: "mid",
    salaryMin: 110000,
    salaryMax: 140000,
    postedDate: "2023-05-12T10:30:00Z",
    applicants: 45,
    skills: ["Product Strategy", "Agile", "User Research", "Roadmapping", "Analytics"],
    companyLogo: "https://ui-avatars.com/api/?name=I&background=5E35B1&color=fff&size=100",
    source: "indeed",
    applyUrl: "https://indeed.com/jobs/view/product-manager"
  },
  {
    id: "3",
    title: "UX/UI Designer",
    company: "DesignHub Creative",
    location: "Austin, TX",
    remote: true,
    description: "DesignHub is looking for a talented UX/UI Designer to create amazing user experiences. You will be responsible for the design system, user research, wireframing, and prototyping. The ideal candidate has a strong portfolio demonstrating user-centered design thinking and excellent visual design skills.",
    jobType: "full-time",
    experienceLevel: "mid",
    salaryMin: 90000,
    salaryMax: 120000,
    postedDate: "2023-05-15T09:15:00Z",
    applicants: 63,
    skills: ["Figma", "User Research", "Prototyping", "Design Systems", "Adobe Creative Suite"],
    companyLogo: "https://ui-avatars.com/api/?name=D&background=00897B&color=fff&size=100",
    source: "glassdoor",
    applyUrl: "https://glassdoor.com/jobs/view/ux-ui-designer"
  },
  {
    id: "4",
    title: "Data Scientist",
    company: "DataInsights Analytics",
    location: "Boston, MA",
    remote: true,
    description: "DataInsights is seeking a Data Scientist to join our analytics team. You will develop machine learning models, analyze large datasets, and provide actionable insights to drive business decisions. The ideal candidate has strong statistical knowledge, programming skills, and experience with machine learning frameworks.",
    jobType: "full-time",
    experienceLevel: "senior",
    salaryMin: 130000,
    salaryMax: 170000,
    postedDate: "2023-05-08T14:45:00Z",
    applicants: 52,
    skills: ["Python", "Machine Learning", "SQL", "TensorFlow", "Data Visualization"],
    companyLogo: "https://ui-avatars.com/api/?name=D&background=E53935&color=fff&size=100",
    source: "linkedin",
    applyUrl: "https://linkedin.com/jobs/view/data-scientist"
  },
  {
    id: "5",
    title: "Frontend Developer",
    company: "WebSolutions Inc",
    location: "Seattle, WA",
    remote: false,
    description: "WebSolutions is looking for a Frontend Developer to build responsive and interactive web applications. You will work with designers to implement user interfaces and ensure cross-browser compatibility. The ideal candidate has strong HTML, CSS, and JavaScript skills with experience in modern frontend frameworks.",
    jobType: "full-time",
    experienceLevel: "mid",
    salaryMin: 95000,
    salaryMax: 125000,
    postedDate: "2023-05-14T11:20:00Z",
    applicants: 38,
    skills: ["React", "JavaScript", "HTML", "CSS", "Responsive Design"],
    companyLogo: "https://ui-avatars.com/api/?name=W&background=039BE5&color=fff&size=100",
    source: "indeed",
    applyUrl: "https://indeed.com/jobs/view/frontend-developer"
  },
  {
    id: "6",
    title: "DevOps Engineer",
    company: "CloudNative Systems",
    location: "Remote",
    remote: true,
    description: "CloudNative Systems is seeking a DevOps Engineer to build and maintain our cloud infrastructure. You will automate deployment pipelines, manage containerized applications, and ensure system reliability. The ideal candidate has experience with cloud platforms, containerization, and infrastructure as code.",
    jobType: "full-time",
    experienceLevel: "senior",
    salaryMin: 125000,
    salaryMax: 165000,
    postedDate: "2023-05-11T13:10:00Z",
    applicants: 29,
    skills: ["AWS", "Kubernetes", "Docker", "Terraform", "CI/CD"],
    companyLogo: "https://ui-avatars.com/api/?name=C&background=546E7A&color=fff&size=100",
    source: "google",
    applyUrl: "https://careers.google.com/jobs/view/devops-engineer"
  },
  {
    id: "7",
    title: "Marketing Specialist",
    company: "GrowthMarketing Agency",
    location: "Chicago, IL",
    remote: false,
    description: "GrowthMarketing is looking for a Marketing Specialist to develop and implement marketing campaigns. You will create content, manage social media, and analyze campaign performance. The ideal candidate has experience with digital marketing channels and strong analytical skills.",
    jobType: "full-time",
    experienceLevel: "entry",
    salaryMin: 60000,
    salaryMax: 80000,
    postedDate: "2023-05-16T09:30:00Z",
    applicants: 42,
    skills: ["Digital Marketing", "Social Media", "Content Creation", "SEO", "Analytics"],
    companyLogo: "https://ui-avatars.com/api/?name=G&background=7CB342&color=fff&size=100",
    source: "glassdoor",
    applyUrl: "https://glassdoor.com/jobs/view/marketing-specialist"
  },
  {
    id: "8",
    title: "Backend Developer",
    company: "ServerStack Technologies",
    location: "Denver, CO",
    remote: true,
    description: "ServerStack is seeking a Backend Developer to build scalable and efficient server-side applications. You will design APIs, implement database solutions, and optimize application performance. The ideal candidate has experience with server-side languages, databases, and API design.",
    jobType: "full-time",
    experienceLevel: "mid",
    salaryMin: 100000,
    salaryMax: 135000,
    postedDate: "2023-05-13T15:45:00Z",
    applicants: 31,
    skills: ["Node.js", "Python", "SQL", "NoSQL", "RESTful APIs"],
    companyLogo: "https://ui-avatars.com/api/?name=S&background=3949AB&color=fff&size=100",
    source: "linkedin",
    applyUrl: "https://linkedin.com/jobs/view/backend-developer"
  },
  {
    id: "9",
    title: "Project Manager",
    company: "AgileWorks Consulting",
    location: "Atlanta, GA",
    remote: false,
    description: "AgileWorks is looking for a Project Manager to lead software development projects. You will coordinate team activities, manage project timelines, and ensure deliverables meet quality standards. The ideal candidate has experience with agile methodologies and excellent communication skills.",
    jobType: "full-time",
    experienceLevel: "senior",
    salaryMin: 110000,
    salaryMax: 140000,
    postedDate: "2023-05-09T10:15:00Z",
    applicants: 27,
    skills: ["Agile", "Scrum", "Project Planning", "Risk Management", "Stakeholder Communication"],
    companyLogo: "https://ui-avatars.com/api/?name=A&background=5E35B1&color=fff&size=100",
    source: "indeed",
    applyUrl: "https://indeed.com/jobs/view/project-manager"
  },
  {
    id: "10",
    title: "QA Engineer",
    company: "QualityFirst Software",
    location: "Portland, OR",
    remote: true,
    description: "QualityFirst is seeking a QA Engineer to ensure the quality of our software products. You will design and execute test plans, automate testing processes, and identify and report bugs. The ideal candidate has experience with testing methodologies and automation tools.",
    jobType: "full-time",
    experienceLevel: "mid",
    salaryMin: 90000,
    salaryMax: 120000,
    postedDate: "2023-05-15T13:30:00Z",
    applicants: 19,
    skills: ["Selenium", "Jest", "Manual Testing", "Test Planning", "JIRA"],
    companyLogo: "https://ui-avatars.com/api/?name=Q&background=00ACC1&color=fff&size=100",
    source: "google",
    applyUrl: "https://careers.google.com/jobs/view/qa-engineer"
  },
  {
    id: "11",
    title: "Mobile App Developer",
    company: "AppGenius Mobile",
    location: "Los Angeles, CA",
    remote: false,
    description: "AppGenius is looking for a Mobile App Developer to build native iOS and Android applications. You will collaborate with designers and backend developers to create seamless mobile experiences. The ideal candidate has experience with Swift, Kotlin, or React Native.",
    jobType: "full-time",
    experienceLevel: "mid",
    salaryMin: 100000,
    salaryMax: 130000,
    postedDate: "2023-05-12T09:45:00Z",
    applicants: 36,
    skills: ["iOS", "Android", "Swift", "Kotlin", "React Native"],
    companyLogo: "https://ui-avatars.com/api/?name=A&background=F4511E&color=fff&size=100",
    source: "glassdoor",
    applyUrl: "https://glassdoor.com/jobs/view/mobile-app-developer"
  },
  {
    id: "12",
    title: "Content Writer",
    company: "ContentCraft Studios",
    location: "Remote",
    remote: true,
    description: "ContentCraft is seeking a Content Writer to create engaging and informative content for various platforms. You will research topics, write articles, and edit content to ensure quality and consistency. The ideal candidate has excellent writing skills and experience with SEO best practices.",
    jobType: "part-time",
    experienceLevel: "entry",
    salaryMin: 40000,
    salaryMax: 60000,
    postedDate: "2023-05-16T14:20:00Z",
    applicants: 51,
    skills: ["Content Writing", "SEO", "Editing", "Research", "Blogging"],
    companyLogo: "https://ui-avatars.com/api/?name=C&background=8E24AA&color=fff&size=100",
    source: "indeed",
    applyUrl: "https://indeed.com/jobs/view/content-writer"
  },
  {
    id: "13",
    title: "Data Analyst",
    company: "InsightAnalytics",
    location: "Dallas, TX",
    remote: true,
    description: "InsightAnalytics is looking for a Data Analyst to transform data into actionable insights. You will collect, process, and analyze data to support business decisions. The ideal candidate has strong analytical skills and experience with data visualization tools.",
    jobType: "full-time",
    experienceLevel: "mid",
    salaryMin: 85000,
    salaryMax: 110000,
    postedDate: "2023-05-14T11:15:00Z",
    applicants: 33,
    skills: ["SQL", "Excel", "Tableau", "Power BI", "Statistical Analysis"],
    companyLogo: "https://ui-avatars.com/api/?name=I&background=00897B&color=fff&size=100",
    source: "linkedin",
    applyUrl: "https://linkedin.com/jobs/view/data-analyst"
  },
  {
    id: "14",
    title: "HR Specialist",
    company: "PeopleFirst HR",
    location: "Miami, FL",
    remote: false,
    description: "PeopleFirst is seeking an HR Specialist to support our human resources operations. You will assist with recruitment, onboarding, employee relations, and HR administration. The ideal candidate has knowledge of HR practices and excellent interpersonal skills.",
    jobType: "full-time",
    experienceLevel: "entry",
    salaryMin: 55000,
    salaryMax: 75000,
    postedDate: "2023-05-15T10:30:00Z",
    applicants: 28,
    skills: ["Recruitment", "Onboarding", "Employee Relations", "HRIS", "Benefits Administration"],
    companyLogo: "https://ui-avatars.com/api/?name=P&background=7B1FA2&color=fff&size=100",
    source: "google",
    applyUrl: "https://careers.google.com/jobs/view/hr-specialist"
  },
  {
    id: "15",
    title: "Network Engineer",
    company: "ConnectTech Networks",
    location: "Phoenix, AZ",
    remote: false,
    description: "ConnectTech is looking for a Network Engineer to design, implement, and maintain our network infrastructure. You will configure network devices, troubleshoot issues, and ensure network security. The ideal candidate has experience with network protocols, security, and monitoring tools.",
    jobType: "full-time",
    experienceLevel: "senior",
    salaryMin: 115000,
    salaryMax: 145000,
    postedDate: "2023-05-10T15:45:00Z",
    applicants: 22,
    skills: ["Cisco", "Routing", "Switching", "Network Security", "Troubleshooting"],
    companyLogo: "https://ui-avatars.com/api/?name=C&background=0288D1&color=fff&size=100",
    source: "glassdoor",
    applyUrl: "https://glassdoor.com/jobs/view/network-engineer"
  },
  {
    id: "16",
    title: "Graphic Designer",
    company: "CreativeVision Design",
    location: "Remote",
    remote: true,
    description: "CreativeVision is seeking a Graphic Designer to create visual concepts for various media. You will design layouts, create illustrations, and develop brand assets. The ideal candidate has a strong portfolio demonstrating creativity and proficiency with design software.",
    jobType: "contract",
    experienceLevel: "mid",
    salaryMin: 70000,
    salaryMax: 90000,
    postedDate: "2023-05-13T09:15:00Z",
    applicants: 47,
    skills: ["Adobe Creative Suite", "Typography", "Branding", "Illustration", "Layout Design"],
    companyLogo: "https://ui-avatars.com/api/?name=C&background=D81B60&color=fff&size=100",
    source: "indeed",
    applyUrl: "https://indeed.com/jobs/view/graphic-designer"
  },
  {
    id: "17",
    title: "Sales Representative",
    company: "GrowthSales Inc",
    location: "Chicago, IL",
    remote: false,
    description: "GrowthSales is looking for a Sales Representative to generate leads and close deals. You will prospect potential clients, conduct product demonstrations, and negotiate contracts. The ideal candidate has strong communication skills and a proven sales track record.",
    jobType: "full-time",
    experienceLevel: "entry",
    salaryMin: 50000,
    salaryMax: 80000,
    postedDate: "2023-05-16T13:45:00Z",
    applicants: 31,
    skills: ["Sales", "Negotiation", "CRM", "Lead Generation", "Relationship Building"],
    companyLogo: "https://ui-avatars.com/api/?name=G&background=43A047&color=fff&size=100",
    source: "linkedin",
    applyUrl: "https://linkedin.com/jobs/view/sales-representative"
  },
  {
    id: "18",
    title: "Full Stack Developer",
    company: "FullStack Solutions",
    location: "Remote",
    remote: true,
    description: "FullStack Solutions is seeking a Full Stack Developer to build end-to-end web applications. You will work on both frontend and backend components, implement features, and optimize performance. The ideal candidate has experience with modern web technologies and frameworks.",
    jobType: "full-time",
    experienceLevel: "mid",
    salaryMin: 100000,
    salaryMax: 140000,
    postedDate: "2023-05-11T10:30:00Z",
    applicants: 39,
    skills: ["JavaScript", "React", "Node.js", "SQL", "Git"],
    companyLogo: "https://ui-avatars.com/api/?name=F&background=3949AB&color=fff&size=100",
    source: "google",
    applyUrl: "https://careers.google.com/jobs/view/full-stack-developer"
  },
  {
    id: "19",
    title: "Customer Support Specialist",
    company: "SupportHub Services",
    location: "Austin, TX",
    remote: true,
    description: "SupportHub is looking for a Customer Support Specialist to assist customers with product inquiries and issues. You will respond to customer queries, troubleshoot problems, and provide solutions. The ideal candidate has excellent communication skills and a customer-focused attitude.",
    jobType: "full-time",
    experienceLevel: "entry",
    salaryMin: 45000,
    salaryMax: 65000,
    postedDate: "2023-05-15T14:15:00Z",
    applicants: 26,
    skills: ["Customer Service", "Problem Solving", "Communication", "Ticketing Systems", "Product Knowledge"],
    companyLogo: "https://ui-avatars.com/api/?name=S&background=00ACC1&color=fff&size=100",
    source: "glassdoor",
    applyUrl: "https://glassdoor.com/jobs/view/customer-support-specialist"
  },
  {
    id: "20",
    title: "Business Analyst",
    company: "AnalyticsEdge Consulting",
    location: "Seattle, WA",
    remote: false,
    description: "AnalyticsEdge is seeking a Business Analyst to bridge the gap between business needs and technical solutions. You will gather requirements, analyze processes, and recommend improvements. The ideal candidate has strong analytical skills and experience with business process modeling.",
    jobType: "full-time",
    experienceLevel: "mid",
    salaryMin: 90000,
    salaryMax: 120000,
    postedDate: "2023-05-12T11:45:00Z",
    applicants: 34,
    skills: ["Requirements Gathering", "Process Modeling", "Data Analysis", "SQL", "Documentation"],
    companyLogo: "https://ui-avatars.com/api/?name=A&background=00897B&color=fff&size=100",
    source: "indeed",
    applyUrl: "https://indeed.com/jobs/view/business-analyst"
  }
];